In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr1.shape

(5,)

In [4]:
arr1.ndim

1

In [5]:
arr1.size

5

In [6]:
arr1.itemsize

4

In [7]:
arr1.dtype

dtype('int32')

-

In [8]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr2.shape

(2, 3)

In [10]:
arr2.ndim

2

In [11]:
arr2.size

6

In [12]:
arr2.itemsize

4

In [13]:
arr2.dtype

dtype('int32')

-

In [14]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
arr3.shape

(2, 2, 2)

In [16]:
arr3.ndim

3

In [17]:
arr3.size

8

In [18]:
arr3.itemsize

4

In [19]:
arr3.dtype

dtype('int32')

-

In [20]:
arr4 = np.linspace(10,20,10)
arr4

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [21]:
arr4.itemsize

8

In [22]:
arr4.dtype

dtype('float64')

-

In [23]:
arr1.dtype

dtype('int32')

In [24]:
arr1.astype('float')

array([1., 2., 3., 4., 5.])

In [25]:
arr1

array([1, 2, 3, 4, 5])